### ISSUE TITLE
Ability to turn theme wrapper on and off.

### ISSUE THREAD

**Issue by riceguitar** [riceguitar/notedeck#7]

**Comment by riceguitar** [comment]
I wonder if it's possible to include the admin bar even with the theme turned off.

**Comment by terrancewoest** [comment]
I was able to get the admin bar there by including wp-footer in the page. Got it in the theme using a filter and 'the_content' hook. Just returned the deck in place of the content. The only issue though is that in order to show up correctly notedeck needs bootstraps container and col functionality. Currently it is including everything with bootstrap. I'm thinking we can just make a custom bootstrap that doesn't mess with the theme cause it only includes what we need. I will put it in as a new issue and close this one.
